export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    VERIFY_OTP: '/auth/verify-otp',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    REFRESH_TOKEN: '/auth/refresh-token',
    LOGOUT: '/auth/logout',
    ME: '/auth/me',
    PROFILE: '/auth/profile',
    SETTINGS: '/auth/settings',
    CHANGE_PASSWORD: '/auth/change-password',
    CHANGE_PASSWORD_REQUEST_OTP: '/auth/change-password-request-otp',
    AVATAR: '/auth/avatar',
    PUBLIC_PROFILE: (id: string) => `/auth/user/${id}`,
    FOLLOW: (id: string) => `/auth/user/${id}/follow`,
    FOLLOWERS: (id: string) => `/auth/user/${id}/followers`,
    FOLLOWING: (id: string) => `/auth/user/${id}/following`,
  },
  PRAYER: {
    TIMES: '/prayer/times',
    HIJRI: '/prayer/hijri',
    EVENTS: '/prayer/events',
    LOG: '/prayer/log',
    LOGS: '/prayer/logs',
    HISTORY: '/prayer/history',
  },
  POSTS: {
    FEED: '/posts/feed',
    CATEGORIES: '/posts/categories',
    BOOKMARKS: '/posts/bookmarks/all',
    LIKED_POSTS: '/posts/likes/all',
    CREATE: '/posts',
    LIKE: (id: string) => `/posts/${id}/like`,
    BOOKMARK: (id: string) => `/posts/${id}/bookmark`,
    COMMENTS: (id: string) => `/posts/${id}/comments`,
    DELETE: (id: string) => `/posts/${id}`,
  },
  MASJID: {
    NEARBY: '/masjid/nearby',
    BOOKMARKS: '/masjid/bookmarks/all',
    BOOKMARK: (id: string) => `/masjid/${id}/bookmark`,
    REVIEWS: (id: string) => `/masjid/${id}/reviews`,
    REVIEW_SUMMARY: (id: string) => `/masjid/${id}/reviews/summary`,
    DELETE_REVIEW: (reviewId: string) => `/masjid/reviews/${reviewId}`,
  },
};
